### ISSUE TITLE
allow rootless operation

### ISSUE THREAD

**Issue by rthallisey** [automationbroker/sbcli#57]
Copy of https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/issues/188

"Hi, it is important to allow rootless operation of the tool. In many corporate environments the users are not allowed to have root. Having access to dockersocket makes easy for user to obtain root privileges.

Perhaps look at [rootless containers](https://www.cyphar.com/blog/post/20160627-rootless-containers-with-runc)?"

**Comment by dymurray** [comment]
This shouldn't be an issue for `sbcli`. We are not using Docker at all and will instead tie into the OpenShift build process.

**Comment by jianzhangbjz** [comment]
Sounds great! Thanks!

**Comment by jianzhangbjz** [comment]
@dymurray one question, do you mean the `sbcli` tool will instead of the `apb` tool in 3.11 version?

**Comment by dymurray** [comment]
@jianzhangbjz yes we plan to deprecate `apb` in 3.11 and instead ship `sbcli`. This is not set in stone yet but is our current plan.

**Comment by jianzhangbjz** [comment]
@dymurray Got it, thanks!
